name: asif123456
on:
  branch_protection_rule:
    types: ["created","edited","deleted"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "from branch protection event triggered workflow"
